version: '3.8'
services:
  mysqldblesson8:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - './data_mysql:/var/lib/mysql'
      - './src/test/resources:/docker-entrypoint-initdb.d'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
